Vagrant.configure("2") do |config|
  config.vm.box = "wesdemos/centos9s-arm"
  config.vm.hostname = "vm"
  config.vm.network "private_network", ip: "192.168.66.66"

  # 设置虚拟机的CPU和内存资源限制
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = "8192"
  end

  # 安装yum工具并设置阿里云yum镜像源
  config.vm.provision "shell", inline: <<-SHELL
    # 安装yum工具
    sudo yum install -y yum-utils

    # 设置阿里云yum镜像源
    # sudo yum-config-manager --add-repo https://mirrors.aliyun.com/repo/Centos-9.repo
    sudo yum-config-manager --add-repo https://mirrors.aliyun.com/repo/epel-7.repo
    sudo yum makecache
  SHELL

  # 安装nodejs16版本
  config.vm.provision "shell", inline: <<-SHELL
    # 添加nodesource yum源
    curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -

    # 安装nodejs
    sudo yum install -y nodejs
  SHELL

   # 安装mongodb4.x版本
   config.vm.provision "shell", inline: <<-SHELL
   # 添加mongodb yum源
   sudo cat > /etc/yum.repos.d/mongodb-org-4.4.repo << EOF
[mongodb-org-4.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/4.4/aarch64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
EOF

   # 安装mongodb
   sudo yum install -y mongodb-org
 SHELL

end
