Vagrant.configure("2") do |config|

  # 配置了端口转发的虚拟机，主要用来测试 host 的网络模式
  config.vm.define "forwarded" do |forwarded|
    forwarded.vm.box = "jouryjc0409/aarch-docker-env"
    forwarded.vm.network "private_network", ip: "192.168.33.31"

    forwarded.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "192.168.1.100"
  end

  # 正常测试的虚拟机配置
  config.vm.define "default" do |test|
    test.vm.box = "jouryjc0409/aarch-docker-env"
    test.vm.network "private_network", ip: "192.168.33.33"
  end
end