Vagrant.configure("2") do |config|
  config.vm.box = "jouryjc0409/aarch-docker-env"
  config.vm.box_version = "1.0.0"

  # 固定虚拟机IP为192.168.33.30
  config.vm.network "private_network", ip: "192.168.33.30"

  # 安装 netstat 工具
  config.vm.provision "shell", inline: <<-SHELL
    # 更新包
    sudo yum -y update
    # 安装网络的调试工具
    sudo yum -y install net-tools lsof
  SHELL
end