Vagrant.configure("2") do |config|
  # 小余的个人PC是M1系统的，所以使用arm架构的centos9，如果是window或者linux，可以前往Vagrant Cloud搜索
  config.vm.box = "jdputsch/centos-9-aarch64"  #config.vm.box = "generic/centos9s"
  config.vm.hostname = "xiaoyu"
  # 固定虚拟机IP，可以通过这个IP访问虚拟机
  config.vm.network "private_network", ip: "192.168.33.33"
  # 将docker-compose程序丢进虚拟机里面ns  
  config.vm.synced_folder ".", "/home/docker-compose", exclude: [".vagrant"]

  # 虚拟机启动之后，执行setup脚本，主要用来安装docker工具
  config.vm.provision "shell", path: "setup.sh"
end